"""First migration

Revision ID: bbb7f3dbfb47
Revises: 
Create Date: 2026-09-07 13:13:34.253662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb7f3dbfb47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendente_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atendente_id'], ['atendente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_atendimento', sa.Integer(), nullable=False),
    sa.Column('valor_a_pagar', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_atendimento'], ['atendimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_commanda', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_commanda'], ['comanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    op.drop_table('comanda')
    op.drop_table('atendimento')
    op.drop_table('atendente')
    # ### end Alembic commands ###
